{% set name = "nfinder" %}
{% set version = "0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nfinder-{{ version }}.tar.gz
  sha256: 8d4d27c30b7104306a795c6d5c3b094c9522710dbd0beda08bdc2e644f6c15b6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm
  run:
    - magicgui
    - matplotlib-base
    - napari
    - napari-plugin-engine
    - numpy
    - pandas
    - python >={{ python_min }}
    - scikit-image
    - scipy

test:
  imports:
    - nfinder
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/santi-rodriguez/nfinder
  summary: Automatic inference of neighboring cells based on their Delaunay triangulation.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - santi-rodriguez
